Bbdd
astherTrinidad/good-way-pilgrim-back pull request #6
Opened 2021-04-11 15:17 UTC by phmaeso

mirar el código de las entity para ver si se me ha pasado algo

2021-04-11 15:23 UTC, lhior95 requested changes
Cambiar "item" por "quantity" o "amount" para evitar confusiones solamente

2021-04-11 16:25 UTC, astherTrinidad approved these changes

2021-04-11 18:29 UTC, astherTrinidad commented on src/DataFixtures/UserDataFixtures.php
> +class AppFixtures extends Fixture
Habría que cambiar el nombre de la clase por le nombre del archivo "UserDataFixtures"

2021-04-11 18:30 UTC, astherTrinidad commented on src/DataFixtures/UserDataFixtures.php
> +        $user = new $Usuario();
En la creación del objeto usuario, eliminar **$** delante de Usuario

2021-04-12 06:57 UTC, javiercloud approved these changes
muy buen trabajo @phmaeso!

2021-04-12 06:57 UTC, javiercloud commented on src/DataFixtures/UserDataFixtures.php
> +        $user->setPass("pass");
Para la aproximación a las fixtures esta bien, luego tendreis que ver como encriptar el pass.

2021-04-12 06:57 UTC, javiercloud commented on src/Entity/Camino.php
> +    private $userCaminos;
muy bien! en prural porque es un arrayCollection

2021-04-12 07:55 UTC, lhior95 approved these changes

2021-04-12 08:23 UTC, merged